controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

nowo_workflow:
    resource: '@NowoWorkflowBundle/Resources/config/routes.yaml'

when@dev:
    nowo_twig_inspector:
        resource: '@NowoTwigInspectorBundle/Resources/config/routes.yaml'
