nowo_workflow_dashboard:
    resource: '../../Controller/DashboardController.php'
    type: attribute
    prefix: '%nowo_workflow.ui.path%'

nowo_workflow_definitions:
    resource: '../../Controller/WorkflowDefinitionController.php'
    type: attribute
    prefix: '%nowo_workflow.ui.path%'

nowo_workflow_locale:
    resource: '../../Controller/LocaleController.php'
    type: attribute
    prefix: '%nowo_workflow.ui.path%'
