services:
    _defaults:
        autowire: true
        autoconfigure: true

    Nowo\WorkflowBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../NowoWorkflowBundle.php'

    Nowo\WorkflowBundle\Repository\:
        resource: '../../Repository/'

    Nowo\WorkflowBundle\Command\:
        resource: '../../Command/'
        tags: ['console.command']

    Nowo\WorkflowBundle\Service\LocaleManager:
        arguments:
            $enabledLocales: '%nowo_workflow.ui.locales%'
            $defaultLocale: '%nowo_workflow.ui.default_locale%'

    Nowo\WorkflowBundle\Service\AllowAllWorkflowUiAccessChecker: ~

    Nowo\WorkflowBundle\Contract\WorkflowUiAccessCheckerInterface:
        alias: Nowo\WorkflowBundle\Service\AllowAllWorkflowUiAccessChecker

    Nowo\WorkflowBundle\Doctrine\TableNamePrefixer:
        arguments:
            $tablePrefix: '%nowo_workflow.table_prefix%'

    Nowo\WorkflowBundle\Doctrine\TablePrefixSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Nowo\WorkflowBundle\Contract\WorkflowRegistryInterface: '@Nowo\WorkflowBundle\Service\DatabaseWorkflowRegistry'
